# Base stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081
 
# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
 
# Corrected COPY command for VMS.csproj
COPY VMS.csproj ./
RUN dotnet restore "./VMS.csproj"
 
# Copy the rest of the application files
COPY . .
WORKDIR "/src"
RUN dotnet build "VMS.csproj" -c $BUILD_CONFIGURATION -o /app/build
 
# Publish stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "VMS.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false
 
# Final stage
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "VMS.dll"]